CREATE TABLE USER
(
    ID   NUMBER           NOT NULL,
    USERNAME VARCHAR2(64) NOT NULL UNIQUE,
    CONSTRAINT PK_USER PRIMARY KEY (ID)
);
CREATE SEQUENCE USER_SEQ start with 1 increment by 1;

CREATE TABLE SECRET
(
    ID   NUMBER               NOT NULL,
    CONTENT VARCHAR2(144 CHAR) NOT NULL UNIQUE,
    OWNER_ID NUMBER,
    CONSTRAINT FK_SECRET_USER foreign key (OWNER_ID) references USER (ID),
    CONSTRAINT PK_SECRET PRIMARY KEY (ID)
);
CREATE SEQUENCE SECRET_SEQ start with 1 increment by 1;
