CREATE TABLE "DIVISION" (
	"ID" NUMBER NOT NULL,
	"NAME" VARCHAR2(255) NOT NULL,
	"ORIGINAL_ NAME" VARCHAR2(255) NOT NULL,
	"DIRECTOR_NAME_ID" NUMBER NOT NULL,
	"PARENT_DIVISION_ID" NUMBER,
	constraint DIVISION_PK PRIMARY KEY ("ID"));


/
CREATE TABLE "PARKING_LOT" (
	"ID" NUMBER NOT NULL,
	"DIVISION_ID" NUMBER NOT NULL,
	"NAME" VARCHAR2(255) NOT NULL,
	"MAX_CAPACITY" NUMBER NOT NULL,
	"CONTACT_PERSON_ID" NUMBER NOT NULL,
	"CATEGORY" VARCHAR2(255) NOT NULL,
	"PRICE_PER_HOUR" BINARY_DOUBLE NOT NULL,
	constraint PARKING_LOT_PK PRIMARY KEY ("ID"));


/
CREATE TABLE "CONTACT_PERSON" (
	"ID" NUMBER NOT NULL,
	"NAME_ID" NUMBER NOT NULL,
	"EMAIL" VARCHAR2(255) NOT NULL,
	"ADDRESS_ID" NUMBER NOT NULL,
	"MOBILE_NR" VARCHAR2(255),
	"PHONE_NR" VARCHAR2(255),
	constraint CONTACT_PERSON_PK PRIMARY KEY ("ID"));


/
CREATE TABLE "MEMBER" (
	"ID" NUMBER NOT NULL,
	"NAME_ID" NUMBER NOT NULL,
	"PHONE_NR" VARCHAR2(255) NOT NULL,
	"ADDRESS_ID" NUMBER NOT NULL,
	"EMAIL" VARCHAR2(255) NOT NULL,
	"LICENSE_PLATE_ID" NUMBER NOT NULL,
	"REGISTRATION_DATE" DATE NOT NULL,
	"MEMBER_LEVEL" VARCHAR2(255) NOT NULL,
	constraint MEMBER_PK PRIMARY KEY ("ID"));


/
CREATE TABLE "NAME" (
	"ID" NUMBER NOT NULL,
	"FIRST_NAME" VARCHAR2(255) NOT NULL,
	"LAST_NAME" VARCHAR2(255) NOT NULL,
	constraint NAME_PK PRIMARY KEY ("ID"));


/
CREATE TABLE "ADDRESS" (
	"ID" NUMBER NOT NULL,
	"STREET_NAME" VARCHAR2(255) NOT NULL,
	"STREET_NUMBER" VARCHAR2(255) NOT NULL,
	"CITY_ID" NUMBER NOT NULL,
	constraint ADDRESS_PK PRIMARY KEY ("ID"));


/
CREATE TABLE "CITY" (
	"CITY_ID" NUMBER NOT NULL,
	"POSTAL_CODE" VARCHAR2(255) NOT NULL,
	"NAME" VARCHAR2(255) NOT NULL,
	constraint CITY_PK PRIMARY KEY ("CITY_ID"));


/
CREATE TABLE "LICENSE_PLATE" (
	"ID" NUMBER NOT NULL,
	"LICENSE_NR" VARCHAR2(255) NOT NULL,
	"ISSUING_COUNTRY" VARCHAR2(255) NOT NULL,
	constraint LICENSE_PLATE_PK PRIMARY KEY ("ID"));


/
ALTER TABLE "DIVISION" ADD CONSTRAINT "DIVISION_fk0" FOREIGN KEY ("DIRECTOR_NAME_ID") REFERENCES "NAME"("ID");
ALTER TABLE "DIVISION" ADD CONSTRAINT "DIVISION_fk1" FOREIGN KEY ("PARENT_DIVISION_ID") REFERENCES "DIVISION"("ID");

ALTER TABLE "PARKING_LOT" ADD CONSTRAINT "PARKING_LOT_fk0" FOREIGN KEY ("DIVISION_ID") REFERENCES "DIVISION"("ID");
ALTER TABLE "PARKING_LOT" ADD CONSTRAINT "PARKING_LOT_fk1" FOREIGN KEY ("CONTACT_PERSON_ID") REFERENCES "CONTACT_PERSON"("ID");

ALTER TABLE "CONTACT_PERSON" ADD CONSTRAINT "CONTACT_PERSON_fk0" FOREIGN KEY ("NAME_ID") REFERENCES "NAME"("ID");
ALTER TABLE "CONTACT_PERSON" ADD CONSTRAINT "CONTACT_PERSON_fk1" FOREIGN KEY ("ADDRESS_ID") REFERENCES "ADDRESS"("ID");

ALTER TABLE "MEMBER" ADD CONSTRAINT "MEMBER_fk0" FOREIGN KEY ("NAME_ID") REFERENCES "NAME"("ID");
ALTER TABLE "MEMBER" ADD CONSTRAINT "MEMBER_fk1" FOREIGN KEY ("ADDRESS_ID") REFERENCES "ADDRESS"("ID");
ALTER TABLE "MEMBER" ADD CONSTRAINT "MEMBER_fk2" FOREIGN KEY ("LICENSE_PLATE_ID") REFERENCES "LICENSE_PLATE"("ID");

ALTER TABLE "ADDRESS" ADD CONSTRAINT "ADDRESS_fk0" FOREIGN KEY ("CITY_ID") REFERENCES "CITY"("CITY_ID");



